services:
  redis-broker:
    image: redis/redis-stack:latest
    container_name: redis-broker
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
        - "redis-volume:/data"
  minio-storage:
     image: quay.io/minio/minio
     container_name: minio-storage
     ports:
       - "9000:9000"
       - "9001:9001"
     env_file: .env
     command: server /data --console-address ":9001"
     volumes:
       - "minio-volume:/data"
volumes:
  redis-volume:
  minio-volume:       